title: 'Блог Анатолия Гуляева'
author: 'Анатолий Гуляев'
keywords: 'kaneru, блог, продуктивность, лайфлист, программирование, фронтенд'
description: > # this means to ignore newlines until "note:"
  Пишу про программирование, фронтенд, продуктивность и свою жизнь.
## note:
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: ''
url:  'https://kaneru.me'
twitter_username: 'kaneru__'
title_image: "/assets/images/title_image.png"
email: 'kaneru+blog@fastmail.com'

permalink: :title/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

exclude:
- README.md

safe: true
lsi: false

include: [_pages]

paginate: 5
paginate_path: "/page:num/"

tag_page: '/tags/'

plugins: [rouge, jekyll-sitemap, jekyll-feed, jekyll-paginate]

future: true

timezone: Asia/Yakutsk
